name: Save Input Parameters as Artifact

on:
  workflow_dispatch:
    inputs:
      param1:
        description: "First input parameter"
        required: true
        default: "default1"
      param2:
        description: "Second input parameter"
        required: true
        default: "default2"

jobs:
  create-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Capture all input parameters and save to file
        run: |
          echo "${{ toJSON(github.event.inputs) }}" > input_parameters.json

      - name: Upload input_parameters.json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: input-parameters-artifact
          path: input_parameters.json

      - name: Download environment variables artifact
        uses: actions/download-artifact@v3
        with:
          name: env_variables_artifact
          path: .

      - name: Load environment variables
        run: |
          # Ensure the variables are set in the environment
          set -a
          source ./env_variables.txt
          set +a

      - name: Display headers passed as environment variables
        run: |
          echo "TESTS_TO_RUN: $TESTS_TO_RUN"
