name: Fetch Input Parameters from Another Run

on:
  workflow_dispatch:
    inputs:
      target_run_id:
        description: 'Target Run ID to fetch input parameters from'
        required: true

jobs:
  fetch-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Fetch Workflow Run Data
        id: fetch_run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_ID=${{ github.event.inputs.target_run_id }}
          REPO=${{ github.repository }}
          echo "Fetching data for run ID: $RUN_ID"
          
          RESPONSE=$(gh api repos/$REPO/actions/runs/$RUN_ID --header "Authorization: token $GITHUB_TOKEN" --jq '.')
          echo "Response: $RESPONSE"
          
          INPUTS=$(echo "$RESPONSE" | jq -r '.event.inputs')
          echo "Inputs: $INPUTS"
          
          echo "::set-output name=inputs::$INPUTS"
