name: Workflow Dispatch - Final Approach

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      abc:
        description: "Some user variable"
        required: true
        default: "123"
      xyz:
        description: "Another user variable"
        required: false
        default: "456"

jobs:
  call-bstack-action:
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup for Rerun'
        id: setup_rerun_vars
        uses: 'browserstack/github-actions/setup-env@O11y-Rerun-Test'
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          github-app: 'bstack-integrations[bot]'

      - name: 'Use of BSTACK Environment Variables if Re-run'
        run: |
            echo "Env variable is: ${{ env.test_to_run }}"

