name: Workflow Dispatch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      is_rerun:
        description: "If re run is enabled or disabled"
        required: true
        default: "disabled"

jobs:
  identify-app-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Rerun Triggered by GitHub App
        id: check-app-trigger
        run: |
          if [[ "${{ github.actor }}" == "GHA-BSTACK-RERUN[bot]" ]]; then
            echo "This rerun was triggered by the GitHub App."
            echo "IS_TRIGGERED_BY_APP=true" >> $GITHUB_ENV
          else
            echo "This rerun was triggered by a different actor."
            echo "IS_TRIGGERED_BY_APP=false" >> $GITHUB_ENV

      - name: Take Action Based on Trigger Source
        if: env.IS_TRIGGERED_BY_APP == 'true'
        run: |
          echo "Performing actions because this was triggered by the GitHub App..."

  check-rerun:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is a re-run
        run: |
          if [ "${{ github.run_attempt }}" -gt 1 ]; then
            echo "This run is a re-run (attempt #${{ github.run_attempt }})."
          else
            echo "This is the first run."
          fi

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build project
        env:
          IS_RERUN: ${{ github.event.inputs.is_rerun }}  # Use input variable here
        run: mvn -B package --file pom.xml -DIS_RERUN=$IS_RERUN
