name: Workflow Dispatch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      is_rerun:
        description: "If re run is enabled or disabled"
        required: true
        default: "disabled"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build project
        env:
          IS_RERUN: ${{ github.event.inputs.is_rerun }}  # Use input variable here
        run: mvn -B package --file pom.xml -DIS_RERUN=$IS_RERUN
