name: Workflow Dispatch - User Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      abc:
        description: "Some user variable"
        required: true
        default: "123"
      xyz:
        description: "Another user variable"
        required: false
        default: "456"
      is_rerun:
        description: "If re run is enabled or disabled"
        required: false
        default: "false"
      tests_to_run:
        description: "The tests to be run"
        required: false
        default: "all"

jobs:
  call-bstack-action:
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup for Rerun'
        id: setup_rerun_vars
        uses: 'browserstack/github-actions/setup-rerun-vars@rerun'
        with:
          run_attempt: ${{ github.run_attempt }}
          repository: ${{ github.repository }}
          run_id: ${{ github.run_id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Run Tests with Updated Parameters'
        run: |
            # Use the environment variable from the previous step
            echo "Running tests: ${{ env.tests_to_run }}"
