name: Repository Dispatch Workflow

on:
  repository_dispatch:
    types: [bstack-rerun]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch || 'main' }}

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build project
        run: mvn -B package --file pom.xml -DIS_RERUN=${{ github.event.client_payload.is_rerun }}
