name: Save Input Parameters as Artifact

on:
  workflow_dispatch:
    inputs:
      param1:
        description: "First input parameter"
        required: true
        default: "default1"
      param2:
        description: "Second input parameter"
        required: true
        default: "default2"

jobs:
  create-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Set parameters from workflow input
        run: |
          echo "param1=${{ github.event.inputs.param1 }}" > input_parameters.txt
          echo "param2=${{ github.event.inputs.param2 }}" >> input_parameters.txt

      - name: Upload input_parameters.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: input-parameters-artifact
          path: input_parameters.txt
