name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      custom_message:
        description: "Custom message to use in the build"
        required: true
      custom_message_1:
        description: "Custom message 1 to use in the build"
        required: false

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Print Custom Message
      run: echo "CUSTOM_MESSAGE is: ${{ github.event.inputs.custom_message }}"

    - name: Print Custom Message 1
      run: echo "CUSTOM_MESSAGE 1 is: ${{ github.event.inputs.custom_message_1 }}"

    - name: Build project with Maven
      env:
        CUSTOM_MESSAGE: ${{ github.event.inputs.custom_message }}
        CUSTOM_MESSAGE_1: ${{ github.event.inputs.custom_message_1 }}
      run: mvn -B package --file pom.xml


