name: Fetch Input Parameters from Another Run

on:
  workflow_dispatch:
    inputs:
      target_run_id:
        description: 'Target Run ID to fetch input parameters from'
        required: true

jobs:
  fetch-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth login --with-token <<< "$GITHUB_TOKEN"

      - name: Fetch Workflow Run Data
        id: fetch_run
        run: |
          RUN_ID=${{ github.event.inputs.target_run_id }}
          REPO=${{ github.repository }}
          echo "Fetching data for run ID: $RUN_ID"
          
          RESPONSE=$(gh api repos/$REPO/actions/runs/$RUN_ID --jq '.')
          echo "Response: $RESPONSE"
          
          INPUTS=$(echo "$RESPONSE" | jq -r '.event.inputs')
          echo "Inputs: $INPUTS"
          
          echo "::set-output name=inputs::$INPUTS"
