name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DAY_OF_WEEK: Monday

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Print Env variable
      run: echo "Hello Darpan. Today is $DAY_OF_WEEK!"

    - name: Print Environment Variable
      run: mvn exec:java -Dexec.mainClass=com.darpan.PrintEnv -Dexec.args="$DAY_OF_WEEK"
      env:
        DAY_OF_WEEK: ${{ secrets.DAY_OF_WEEK }} # Use GitHub Secrets if you want to keep this secure
